### ISSUE TITLE
Fix missing event IDs from Pass 2 export

### ISSUE THREAD

**Issue by davidskalinder** [davidskalinder/mpeds-coder#109]
@johnklemke reports that a lot (hundreds!) of events in the pass 2 export file are missing event IDs somehow.  This can probably be worked around for now, so a fix might not be a high priority, but it's not great.

Probably in the short term it's worth it to debug somewhat to make sure this isn't a symptom of some larger problem?...

**Comment by davidskalinder** [comment]
So looking at these ETL files again I'm pretty sure that the event ID column is blank only when an article has no events in it; so the article info for such articles will appear on only one line with no event information, which I think is the expected behavior.  @johnklemke, does that sound correct based on what you're seeing?

If so, then you should be able to include MAI's event ID for any events (well, event reports, really) that the pass 2 DB creates; though I don't know how much value that adds.  (It might be good to have in there somewhere for reference even if it's not doing much work I think, though perhaps not with very high priority.)  I can't remember the context that occasioned this issue -- if the value isn't clear to you then maybe I could try harder to remember it and see if that helps clarify things!

**Comment by johnklemke** [comment]
Ah! Of course.

The context for this was the logic for importing MAI pass 1 data into 
the Access tblBnpCoderLines. With updates exported from MAI every two 
weeks, we have the problem of when a pass 1 coder's work on a particular 
article spanned the export cutoff (so deciding later in the day or even 
a day or two later to go back to an article they'd been working on 
before the export) we wanted to get the benefit of the coder's 
revisions/new work, etc. without just trashing the work a pass 2 coder 
had already performed in Access. Since some of that work might well 
involve coder lines without an event, I think this just confirms the 
tactic I've adopted -- not looking to identify such "overlaps" by 
matching MAI event IDs, but instead to look out for pass 1 coder/article 
combinations already in the table and taking appropriate actions when 
found.

**Comment by davidskalinder** [comment]
Ah yes, thanks for the reminder.

Sounds like we can close this one then (and of course if there are further issues on the pass 2 side of the ETL we can open them over at https://github.com/davidskalinder/bpp-pass2-ui/issues).
