### ISSUE TITLE
Change MAI contact address

### ISSUE THREAD

**Issue by davidskalinder** [davidskalinder/mpeds-coder#42]
To DS

**Comment by davidskalinder** [comment]
Changed in branches change_contact_address and testing.

@olderwoman and @matthewsmorgan, this is fixed in the testing interface now and I'm moving the issue into user-testing even though it's such a tiny change, since it seems like a good practice to always make sure that mine are not the only set of eyes that have reviewed even a small change before we move it to production?  But if it drives y'all crazy to have to approve stuff this minor and you want me to keep stuff out of user-testing unless I'm nervous about it, let me know...

**Comment by olderwoman** [comment]
Unfortunately, when I click “view it on git” it does not show what the issue is. From the subject line it would seem to be MAI contact address. I can report that this is David Skalinder in the testing environment and still Alex Hanna in the production environment. Clicking on David Skalinder opened an email client.

**Comment by davidskalinder** [comment]
Okay, I'll move it to production, and send you an email about the issue visibility thing.

**Comment by davidskalinder** [comment]
Merged into master and deployed to production.
